### ISSUE TITLE
Sage in About (typo)

### ISSUE THREAD

**Issue by dglaude** [fhoedemakers/pico-smsplus#8]
Except if this intended...

**Comment by fhoedemakers** [comment]
Hi, 

I'm not sure I understand what you mean. Can you explain it a little bit more in detail?
Thanks,

Frank

**Comment by dglaude** [comment]
Page https://github.com/fhoedemakers/pico-smsplus

The About section say:

About
*Sage* Master System Emulator with SD card and menu support for the Raspberry PI Pico/Adafruit Feather RP2040 DVI. Play your games from SD card on a HDMI display.

**Comment by fhoedemakers** [comment]
Ah ok! Is corrected! Thanks!
